### ISSUE TITLE
problème

### ISSUE THREAD

**Issue by gabriel23338** [MartinPELCAT/GlobalExamFinisher#2]
bonjour malgré l'autorisation d'ouvrir plusieurs pop up , la console me met une erreur 

`Uncaught TypeError: Cannot read properties of undefined (reading 'href')
    at <anonymous>:4:30`

**Comment by MartinPELCAT** [comment]
Si ça marche pas du tout ça veux dire que la classe qui "sélectionne" les boutons n'est plus bonne `a.button-outline-primary-small`.
Est-ce que tu es sur la bonne page ? 

Je n'ai plus d'accès à la plateforme je ne peux donc pas tester.

**Comment by MartinPELCAT** [comment]
Je viens de modifier la classe je pense que tu peux tester avec la dernière version.

**Comment by gabriel23338** [comment]
j'ai réessayer , merci beaucoup sa refonctionne !
