### ISSUE TITLE
Problème 

### ISSUE THREAD

**Issue by Kirachiyuki38** [MartinPELCAT/GlobalExamFinisher#4]
bonjour malgré l'autorisation d'ouvrir plusieurs pop up , la console me met une erreur

Uncaught TypeError: Cannot read properties of undefined (reading 'href') at <anonymous>:4:30
 Y’a t il une solution ?

**Comment by MartinPELCAT** [comment]
T'es sur la bonne page ? 
Si oui ouvre les liens (boutons : "lire la fiche") une fois à la main et ça devrait marcher sauf si ils ont changer le code de la page depuis le temps

**Comment by Kirachiyuki38** [comment]
Ça fonctionne correctement ça m’ouvre toute les page de test mais par contre ça ne me valide rien est ce normal ?

**Comment by MartinPELCAT** [comment]
Ils ont peut etre changer la methode de calcul, avant juste ouvrir une page ça comptais comme 5 minutes + 1 activité

**Comment by Kirachiyuki38** [comment]
Mince car là ça m’ouvre bien toute les pages pour faire le test mais ça ne lance pas le test y’a t il une autre solution ?

**Comment by Kirachiyuki38** [comment]
Y’a t il une solution pour validé le parcours général ? C’est surtout ça dont j’ai besoin en fait

**Comment by MartinPELCAT** [comment]
C'est pas ce genre de scripts, celui ci est supposé rien faire à part ouvrir les tests.

J'en avais fait un autre ici pour le mode "parcours" je crois mais je suis pas sur qu'il marche encore.
Celui ci il faut laisser tourner l'onglet sans le fermer


https://github.com/MartinPELCAT/GlobalExamFinisher/tree/business

**Comment by Kirachiyuki38** [comment]
Celui ci me sors une uncaught typeerror au niveau de cette ligne : 

button.click();

le script ne passe donc pas

**Comment by MartinPELCAT** [comment]
C'est le deuxieme block qu'il faut copier pas le permier

**Comment by Kirachiyuki38** [comment]
Oui oui sur le 2 eme 
![Uploading image.jpg…]()

**Comment by Kirachiyuki38** [comment]
« Uncaught TypeError: Cannot read properites of null (reading « click »)

**Comment by MartinPELCAT** [comment]
Ben je ne sais pas alors ça a peut etre changer depuis, va falloir faire les exos à la main

**Comment by Kirachiyuki38** [comment]
Zut j’en ai pour 1 ans :/
